export const SET_TIMETABLE = 'SET_TIMETABLE'
export const SET_ADVERTS = 'SET_ADVERTS'
export const SET_SOCKET = 'SET_SOCKET'
export const RECIEVE_TIMETABLE_PENDING ='RECIEVE_TIMETABLE_PENDING'
export const RECIEVE_TIMETABLE_SUCCESS = 'RECIEVE_TIMETABLE_SUCCESS'
export const RECIEVE_TIMETABLE_FAILED = 'RECIEVE_TIMETABLE_FAILED'
export const MODIFY_TIMETABLE = 'MODIFY_TIMETABLE'


export const RECIEVE_ADVERTS_PENDING ='RECIEVE_ADVERTS_PENDING'
export const RECIEVE_ADVERTS_SUCCESS = 'RECIEVE_ADVERTS_SUCCESS'
export const RECIEVE_ADVERTS_FAILED = 'RECIEVE_ADVERTS_FAILED'

export const SET_EMAIL_FIELD ='SET_EMAIL_FIELD'
export const SET_PASSWORD_FIELD ='SET_PASSWORD_FIELD'
export const SET_IMAGE_FIELD = 'SET_IMAGE_FIELD';

export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED  = 'LOGIN_FAILED'

export const UPLOAD_PENDING = 'UPLOAD_PENDING'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILED  = 'UPLOAD_FAILED'


export const EMAIL_FIELD_ERROR ='EMAIL_FIELD_ERROR'
export const VALID_EMAIL='VALID_EMAIL'

export const DISPLAY_TIMETABLE ='DISPLAY_TIMETABLE'
export const HIDE_TIMETABLE ='HIDE_TIMETABLE'

export const SET_AS_STAFF = 'SET_AS_STAFF'
export const SET_AS_STUDENT = 'SET_AS_STUDENT'

export const LOGOUT = 'LOGOUT'

export const SET_PREVIEW_IMAGE = 'SET_PREVIEW_IMAGE'
export const REMOVE_PREVIEW_IMAGE = 'REMOVE_PREVIEW_IMAGE'
